version: '3'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.15-management
    ports:
      - '5672:5672'
      - '15672:15672'
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --loglevel warning
